apiVersion: v1
kind: Pod
metadata:
  name: pod-probe-demo
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent

    startupProbe:
      exec:
        command: ["/bin/sh","-c","[ \"$(curl -s 127.0.0.1/livez)\" = \"OK\" ]"]
      initialDelaySeconds: 0
      periodSeconds: 2
      timeoutSeconds: 5
      failureThreshold: 30

    livenessProbe:
      httpGet:
        path: /livez
        port: 80
        scheme: HTTP
      initialDelaySeconds: 0
      timeoutSeconds: 5

    readinessProbe:
      httpGet:
        path: /readyz
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      timeoutSeconds: 5
